//
//  DummyTortoise.swift
//  TortoiseApps
//
//  Created by Hadi Nasution on 21/06/21.
//

import UIKit

var tortoise: [Tortoise] = [
    Tortoise(image: UIImage(named: "sulcata")!, title: "Sulcata", desc: "Spesies kura-kura darat dari Afrika, ini adalah spesies kura-kura terbesar ke-3 di Dunia. Kura-kura Sulcata sering dijadikan hewan peliharaan karna mudah dirawat, motif yang lucu dan pakan yang murah, tetapi kura-kura sulcata memiliki harga yang cukup mahal.", habitat: "Darat", status: "Bisa dipelihara", makanan: "Herbivora", harga: "1-10jt"),
    Tortoise(image: UIImage(named: "aldabra")!, title: "Aldabra", desc: "Kura-kura raksasa Aldabra adalah salah satu kura-kura terbesar di dunia. Kura-kura ini hidup di Aldabra. Kura-kura ini dapat tumbuh hingga lebih dari 1.5 meter dan dapat berumur hingga mencapai 200an tahun.", habitat: "Darat", status: "Hewan Dilindungi", makanan: "Herbivora", harga: ">=20jt"),
    Tortoise(image: UIImage(named: "redears")!, title: "Red ears (Kura-kura Brazil)", desc: "Kura-kura brazil dikenal juga sebagai kura-kura red-ear slider atau dalam bahasa latin trachemys scripta elegans. Hal ini disebabkan adanya semburat warna merah tepat di belakang matanya sehingga menyerupai telinga berwarna merah.", habitat: "Air", status: "Bisa dipelihara", makanan: "Omnivora", harga: "10K-500K"),
    Tortoise(image: UIImage(named: "diamondback")!, title: "Diamondback", desc: "Diamondback terrapin atau hanya terrapin adalah spesies penyu asli dari rawa pasang surut pantai timur Amerika Serikat bagian timur dan selatan, dan di Bermuda. Itu milik genus Malaclemys monotipik.", habitat: "Air", status: "Bisa dipelihara", makanan: "Omnivora", harga: "300K-2jt"),
    Tortoise(image: UIImage(named: "galapagos")!, title: "Galapagos", desc: "Kura-kura galápagos atau kura-kura raksasa galapagos adalah spesies kura-kura terbesar yang masih hidup. Kura-kura galápagos modern beratnya bisa mencapai 417 kg.", habitat: "Darat", status: "Hewan Dilindungi", makanan: "Herbivora", harga: ">=20jt"),
    Tortoise(image: UIImage(named: "harmani")!, title: "Harmani", desc: "Kura-kura Hermann adalah spesies dalam genus Testudo. Dua subspesies dikenal: kura-kura Hermann barat dan kura-kura Hermann timur. Terkadang disebut sebagai subspesies, T. h. peleponnesica belum dikonfirmasi secara genetik berbeda dari T. h. boettgeri.", habitat: "Darat", status: "Bisa dipelihara", makanan: "Herbivora", harga: "400k-5jt"),
    Tortoise(image: UIImage(named: "indianstar")!, title: "Indian Star", desc: "Kura-kura bintang India adalah spesies kura-kura terancam yang ditemukan di daerah kering dan menggosok hutan di India, Pakistan dan Sri Lanka. Spesies ini cukup populer dalam perdagangan hewan peliharaan yang eksotis, yang merupakan alasan utama terancam punah", habitat: "Darat", status: "Hewan Dilindungi", makanan: "Herbivora", harga: "tidak diketahui"),
    Tortoise(image: UIImage(named: "pignose")!, title: "Pig Nose", desc: "Labi-labi moncong babi adalah satu-satunya jenis labi-labi yang masih lestari yang merupakan anggota keluarga Caretochelidae.", habitat: "Air", status: "Bisa dipelihara", makanan: "Omnivora", harga: "100K-2jt"),
    Tortoise(image: UIImage(named: "radiata")!, title: "Radiata", desc: "Kura-kura pancaran adalah spesies kura-kura dalam famili Testudinidae. Meskipun spesies ini asli dan paling melimpah di Madagaskar selatan, ia juga dapat ditemukan di seluruh pulau ini, dan telah diperkenalkan ke pulau Réunion dan Mauritius.", habitat: "Darat", status: "Bisa dipelihara", makanan: "Herbivora", harga: "2-50jt"),
    Tortoise(image: UIImage(named: "redfoot")!, title: "Red Foot", desc: "Red footed tortoise (Geochelone Carbonaria) atau Redfoot, Redfoot berasal dari Amerika Selatan dan sangat populer sebagai reptile peliharaan. Nama redfoot sudah bisa ditebak didapatkan dari warna merah atau oranye yang terdapat pada tempurung dan sebagian kepala & ekornya.", habitat: "Darat", status: "Bisa dipelihara", makanan: "Herbivora", harga: "5-50jt"),
    Tortoise(image: UIImage(named: "russian")!, title: "Russian Tortoise", desc: "Kura-kura rusia, juga dikenal dengan nama kura-kura Horsfield atau kura-kura asia tengah, adalah spesies kura-kura dan termasuk hewan peliharaan yang populer", habitat: "Darat", status: "Bisa dipelihara", makanan: "Herbivora", harga: "3-30jt"),
    Tortoise(image: UIImage(named: "tutul")!, title: "Russian Tortoise", desc: "Penyu tutul, satu-satunya spesies dari genus Clemmys, adalah penyu kecil semi-akuatik yang mencapai panjang karapas 8-12 cm setelah dewasa", habitat: "Air", status: "Bisa dipelihara", makanan: "Omnivora", harga: "1-5jt")
]
